blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('', views.article_list, name='article_list'),
    path('<slug:article>/', views.article_full, name='article_full'),
]

tiaclone/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp')),
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

# Create your models here.
class ArticleManager(models.Manager):
    def get_articles(self):
        return super(ArticleManager, self).get_articles().filter(status='active')

class Article(models.Model):
    STATUS_OPTIONS = ( ('active', 'Active'), ('notactive', 'Notactive') )

    title = models.CharField(max_length=255)

    slug = models.SlugField(max_length=250,
                            unique_for_date='created')

    writer = models.ForeignKey(User,
                            on_delete=models.CASCADE,
                            related_name='articles')

    body = models.TextField()

    created = models.DateTimeField(default=timezone.now)

    status = models.CharField(max_length=9,
                            choices=STATUS_OPTIONS)

    picture = models.CharField(max_length=40)

    class Meta:
        ordering = ('-created',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blogapp:article_full',
                        args = [self.slug])

    def get_picture(self):
        return '../../static/img/'+self.picture

    objects = models.Manager()
    active = ArticleManager()

class Comment(models.Model):
    ACTIVE_CHOICES = (
        ('Yes', 'yes'),
        ('No', 'no'),
    )

    article = models.ForeignKey(Article,
                                on_delete=models.CASCADE,
                                related_name="comments")
    name = models.CharField(max_length=255)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    active = models.CharField(max_length=3,
                            choices= ACTIVE_CHOICES)

    class Meta():
        ordering = ('-created',)

    def __str__(self):
        return f"comment by {self.name} on {self.created}"

blogapp/views.py
from django.shortcuts import render, get_object_or_404
from .models import Article
# Create your views here.

def article_list(request):
    articles = Article.active.all()
    return render(request, 'blogapp/article/index.html', {'articles': articles})

def article_full(request, article):
    article = get_object_or_404(Article,slug=article)
    comments = article.comments.all()
    return render(request,'blogapp/article/detail.html', {'article': article, 'comments': comments})

templates/blogapp/article/detail.html
{% extends 'blogapp/base.html' %}

{% block content %}
    <img src="{{ article.get_picture }}" style="width: 100%;"/>
    <h2>{{ article.title }}</h2>
    <article> {{ article.body|linebreaks }} </article>

{% endblock %}

templates/blogapp/article/index.html
{% extends 'blogapp/base.html' %}
{% load static %}

{% block title %} TIA Home Page {% endblock %}

{% block content %}
    {% if articles %}
        <div class="grid-container">
            {% for item  in articles %}
                <a class="Main" href="{{ item.get_absolute_url }}">
                    <img src="{{ item.get_picture }}" style="width: 100%"/>
                    <p>{{ item.title }}</p>
                </a>
            {% endfor %}
        </div>
    {% else %}
        <p>No content</p>
    {% endif %}
{% endblock %}

templates/blogapp/article/links.html
<ul>
    {% for link in links %}
        <li><a href="{{ link.get_absolute_url }}">{{ link.title }}</a></li>
    {% endfor %}
</ul>

templates/blogapp/base.html
{% load blogtags %}
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <title>{% block title %} {% endblock %}</title>
        <link rel="stylesheet" href="{% static 'css/style.css' %}">
        <script src="https://unpkg.com/react@16.7.0/umd/react.development.js"></script>
        <script src="https://unpkg.com/react-dom@16.7.0/umd/react-dom.development.js"></script>
        <script src="https://unpkg.com/@babel/standalone/babel.min.js"></script>
    </head>
    <body>
        <div id="navbar">
            <h2><a href="{% url 'blogapp:article_list' %}">This Is Anfield</a></h2>
            <nav>
                <a href="#">News</a>
                <a href="#">Opinion</a>
                <a href="#">Transfer News</a>
                <a href="#">Calendar</a>
            </nav>
        </div>

        <div id="content">
            {% block content %}{% endblock %}
        </div>
        <div id="sidebar">
            <h2>More content</h2>
            {% show_links %}
        </div>

    </body>
</html>